<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
        
    if len(A[0]) == len(B):
        mul = []
        
        for i in range(0, len(A)):
            row = []
            
            for j in range(0, len(B[0])):
                sum = 0
                for k in range(0, len(B)):
                    
                    sum += A[i][k] * B[k][j] 
                
                row.append(sum)
            mul.append(row)
        
        return mul

        
    return "not possible"
    


A   = [[1,3,4],[2,5,7],[5,9,6]]
B   = [[1,0,0],[0,1,0],[0,0,1]]

C   = [[1,2],[3,4]]
D   = [[1,2,3,4,5],[5,6,7,8,9]]

E   = [[1,2],[3,4]]
F   = [[1,4],[5,6],[7,8],[9,6]]

for row in matrix_mul(A, B):
    print(row)
    
for row in matrix_mul(C, D):
    print(row)
    
print(matrix_mul(E, F))



[1, 3, 4]
[2, 5, 7]
[5, 9, 6]
[11, 14, 17, 20, 23]
[23, 30, 37, 44, 51]
not possible


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [2]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
A = [1, 5, 27, 6, 13, 28, 100, 45, 10, 79]
def pick_a_number(A):
    cum_sum = []
    sum = 0
    
#     cumulative sum
    for i in range(0, len(A)):
        sum = sum + A[i]
        cum_sum.append(sum)
    
    r_num = uniform(1,max(cum_sum))

    for i in range(0, len(A)-1):
        if cum_sum[i] <= r_num < cum_sum[i+1]:
            return A[i+1]
        
        
def do_exp(n,A):
    A.sort()
    lst = []
    dic = dict()
    
    for i in range(n):
        x = pick_a_number(A)
        lst.append(x)
    
    for i in range(len(A)):
        dic[A[i]] = lst.count(A[i])
    for i in dic:
        print(i, "==>",dic[i])

do_exp(100,A)

1 ==> 0
5 ==> 0
6 ==> 0
10 ==> 4
13 ==> 6
27 ==> 5
28 ==> 8
45 ==> 11
79 ==> 32
100 ==> 34


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [3]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    num = re.sub(r'\D',"",String)
    
    return '#' * len(num)

String = "#2a$#b%c%561#"
replace_digits(String)

'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [4]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure

def name(names,marks,arr,start, end):
    lst = []
    val = list(marks.values())
    
    for i in range(start-1, end):
        tempName = names[val.index(arr[i])]
        lst.append(tempName)
    return lst

def display_dash_board(students, marks):
        dicName = dict()
        dicMarks = dict()

        for i in range(len(Students)):
            dicName[i] = Students[i]
            dicMarks[i] = Marks[i]

        marks.sort()

        #getting key from values
        key_list = list(dicMarks.keys())
        val_list = list(dicMarks.values())

        # write code for computing top top 5 students
        top_5_students = name(dicName, dicMarks, marks, len(marks)-5, len(marks))



        # write code for computing top least 5 students
        least_5_students = name(dicName, dicMarks, marks, 1, 5)


        # write code for computing top least 5 students
        students_within_25_and_75 = name(dicName, dicMarks, marks, 3, 7)

        return top_5_students, least_5_students, students_within_25_and_75
    
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(Students, Marks)
print(top_5_students[::-1])
print(least_5_students)
print(students_within_25_and_75)

['student8', 'student10', 'student2', 'student5', 'student7', 'student1']
['student3', 'student4', 'student9', 'student6', 'student1']
['student9', 'student6', 'student1', 'student7', 'student5']


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [5]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure
# here S is list of tuples and P is a tuple ot len=2

import math

def calculate(n,m):
    x = n[0]
    y = n[1]

    p = m[0]
    q = m[1]
    return math.acos(              ( (x*p) + (y*q) )\
    / ( ( math.sqrt((x**2) + (y**2) ) ) * ( math.sqrt( (p**2) + (q**2) ) ) ) )



def closest_points_to_p(S, P):
    dic = dict()
    
    for i in range(len(S)):
        dic[S[i]] = calculate(S[i], P)
    
    arr = list(dic.values())
    val = list(dic.values())
    key = list(dic.keys())
    arr.sort()
    
    closest_points_to_p = []
    for i in range(5):
        point = key[val.index(arr[i])]
        closest_points_to_p.append(point)
    
    return closest_points_to_p

############################################################################3

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

points = closest_points_to_p(S, P)

for i in points:
    print(i)

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [6]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure

import math

def getCor(s):
    
    first = s.split('x')
    a = float(first[0])
    
    second = first[1].split('y')
    b = float(second[0])
    c = float(second[1])
    
    return (a,b,c)


def getSide(t,p):
    
    cal = (t[0] * p[0]) + (t[1] * p[1]) + (t[2])

    if cal > 0:
        return 1
    elif cal < 0:
        return -1
    elif cal == 0:
        return 0
    return -2


def getAns(red,blue,line):
    
    sign_red = getSide(getCor(line),red[0])
    sign_blue = getSide(getCor(line),blue[0])
        
    for j in range(len(red)):
        if sign_red != getSide(getCor(line),red[j]):
            return 'no'

    for j in range(len(blue)):

        if sign_blue != getSide(getCor(line),blue[j]):
            return 'no'
    return 'Yes'


Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    ans = getAns(Red, Blue, i)
    print(ans)

Yes
no
no
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [7]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure

def getStr(st):
    s = st.split(',')
    k = {}
    counter = 0
    lstcounter = 0
    for i in range(len(s)):
        if s[i].isdigit():
            if lstcounter != i:
                k[counter] = (lstcounter,i)
                counter = counter + 1
                lstcounter = i

        if lstcounter < len(s):
            if lstcounter != len(s)-1:
                k[counter] = (lstcounter,len(s)-1)
    
    return k

def getCal(s,d):
    lst = []
    for i in range(len(d)):
        firstIndex = d[i][0]
        secondIndex = d[i][1]
        first_ele = str(s[d[i][0]])
        second_ele = str(s[d[i][1]])

        if first_ele.isdigit() and second_ele.isdigit():
            for j in range(firstIndex, secondIndex + 1):
                s[j] = ((int(first_ele) + int(second_ele)) // (secondIndex - firstIndex + 1))

        elif second_ele.isdigit():
            for j in range(firstIndex, secondIndex + 1):
                s[j] = (( int(second_ele)) // (secondIndex - firstIndex + 1))
        elif first_ele.isdigit():
            for j in range(firstIndex, secondIndex + 1):
                s[j] = (( int(first_ele)) // (secondIndex - firstIndex + 1))
    return s



def getSmootString(string):
    
    indexes = getStr(string)
    lst = getCal(string.split(','),getStr(string))
    
    return lst


a =  "_,_,30,_,_,_,50,_,_"
b = "40,_,_,_,60"
c = "_,_,_,24"
d = "80,_,_,_,_"
e = "10_,_,30,_,_,_,50,_,_,20"


print(getSmootString(a))
print(getSmootString(b))
print(getSmootString(c))
print(getSmootString(d))
print(getSmootString(e))

[10, 10, 12, 12, 12, 12, 4, 4, 4]
[20, 20, 20, 20, 20]
[6, 6, 6, 6]
[16, 16, 16, 16, 16]
[10, 10, 12, 12, 12, 12, 8, 8, 8, 8]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [8]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure

def calculateProb(A,given,find):
    de = 0
    no = 0
    for i in A:
        if i[1] == given:
            de += 1
            if i[0] == find:
                no += 1
    return str(no)+ '/' + str(de)

def compute_conditional_probabilites(A):
    a = ['F1','F2','F3','F4','F5']
    b = ['S1','S2','S3']
    
    for i in range(len(a)):
        for j in range(len(b)):
            print(f"P(F={a[i]}|S=={b[j]})={calculateProb(A,b[j],a[i])} ")
        print()

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F=F1|S==S1)=1/4 
P(F=F1|S==S2)=1/3 
P(F=F1|S==S3)=0/3 

P(F=F2|S==S1)=1/4 
P(F=F2|S==S2)=1/3 
P(F=F2|S==S3)=1/3 

P(F=F3|S==S1)=0/4 
P(F=F3|S==S2)=1/3 
P(F=F3|S==S3)=1/3 

P(F=F4|S==S1)=1/4 
P(F=F4|S==S2)=0/3 
P(F=F4|S==S3)=1/3 

P(F=F5|S==S1)=1/4 
P(F=F5|S==S2)=0/3 
P(F=F5|S==S3)=0/3 



<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [9]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure

def string_features(S1, S2):
    a = 0
    b = []
    c = []
    
    for i in S1.split():
        for j in S2.split():
            
            if i == j:
                a += 1
            else:
                if (i not in S2) and (i not in b):
                    b.append(i)
                    
                elif (j not in S1) and (j not in c):
                    c.append(j)
  
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a)
print(b)
print(c)

7
['first', 'F', '5']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [10]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure

import math

def compute_log_loss(A):
    loss = 0
    for i in A:
        loss += -1 * 1/len(A) * ((i[0]*math.log10(i[1])) + ((1 - i[0]) * math.log10(1- i[1])) )
        
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
